package net.fireboy.mageadditions.mixin;

import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.fireboy.mageadditions.config.CastTimeOverrides;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.loot.LootContext;
import net.neoforged.neoforge.common.CommonHooks;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Final-pass cleanup for loot generated by Iron's Spells 'n Spellbooks.
 *
 * This runs after the complete top-level loot table has generated, which means
 * it also catches items that came from referenced/nested loot tables.  That is
 * important for the Manhunt loot changes because several Iron's structure
 * tables compose smaller helper tables instead of directly listing every item.
 */
@Mixin(value = CommonHooks.class, remap = false)
public abstract class CommonHooksLootMixin {
    private static final ResourceLocation COPPER_SPELL_BOOK =
            ResourceLocation.fromNamespaceAndPath("irons_spellbooks", "copper_spell_book");

    @Inject(
            method = "modifyLoot(Lnet/minecraft/resources/ResourceLocation;Lit/unimi/dsi/fastutil/objects/ObjectArrayList;Lnet/minecraft/world/level/storage/loot/LootContext;)Lit/unimi/dsi/fastutil/objects/ObjectArrayList;",
            at = @At("RETURN")
    )
    private static void mageadditions$applyManhuntLootCleanup(
            ResourceLocation lootTableId,
            ObjectArrayList<ItemStack> generatedLoot,
            LootContext context,
            CallbackInfoReturnable<ObjectArrayList<ItemStack>> cir
    ) {
        if (!CastTimeOverrides.lootChangesEnabled()
                || lootTableId == null
                || !"irons_spellbooks".equals(lootTableId.getNamespace())) {
            return;
        }

        ObjectArrayList<ItemStack> finalLoot = cir.getReturnValue();
        if (finalLoot == null || finalLoot.isEmpty()) {
            return;
        }

        // Remove copper rewards from Iron's loot, including Copper Spell Books
        // produced indirectly by helper/nested tables.
        finalLoot.removeIf(stack -> stack.is(Items.COPPER_INGOT)
                || COPPER_SPELL_BOOK.equals(BuiltInRegistries.ITEM.getKey(stack.getItem())));

        // Turn every normal potion produced by an Iron's loot table into the
        // matching splash bottle. transmuteCopy preserves data components,
        // including POTION_CONTENTS, custom name, count, etc.
        for (int i = 0; i < finalLoot.size(); i++) {
            ItemStack stack = finalLoot.get(i);
            if (stack.is(Items.POTION)) {
                finalLoot.set(i, stack.transmuteCopy(Items.SPLASH_POTION));
            }
        }
    }
}
